version: "3.9"
services:
  verify_yew:
    container_name: verify_yew
    build:
      context: .
      dockerfile: docker/Dockerfile
    entrypoint: trunk serve --address 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verify_yew.rule=Host(`www.i-proof.com.tw`)&&PathPrefix(`/verify`)"
      - "traefik.http.routers.verify_yew.tls=true"
    ports:
      - "3003:8080"
    networks:
      - verify
networks:
  verify:
    external:
      name: traefik-dev